name: vis_utils
channels:
  - pytorch
  - defaults
dependencies:
  - anndata
  - scanpy
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - numba=0.51.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - pandas=1.2.2
  - pip=20.3.3
  - python=3.8.5
  - pytorch=1.7.1
  - scikit-image=0.16.2
  - scikit-learn=0.23.2
  - scipy=1.6.0
  - setuptools=52.0.0
  - torchvision=0.8.2
  - yaml=0.2.5
  - pip:
      - pykeops==1.5